export const CKYC_SEARCH_PROVIDER = Symbol('CKYC_SEARCH_PROVIDER');
export const CKYC_DOWNLOAD_PROVIDER = Symbol('CKYC_DOWNLOAD_PROVIDER');
export const CKYC_UPLOAD_PROVIDER = Symbol('CKYC_UPLOAD_PROVIDER');
export const CKYC_UPDATE_PROVIDER = Symbol('CKYC_UPDATE_PROVIDER');
